version: "3.8"

services:
  fastapi_app1:
    build: .
    ports:
      - "9000:9000"
    command: [ "python", "main.py", "9000" ]

  fastapi_app2:
    build: .
    ports:
      - "9001:9001"
    command: [ "python", "main.py", "9001" ]
  fastapi_app3:
    build: .
    ports:
      - "9002:9002"
    command: [ "python", "main.py", "9002" ]
  fastapi_app4:
      build: .
      ports:
        - "9003:9003"
      command: [ "python", "main.py", "9003" ]

  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8999:8999"
    depends_on:
      - fastapi_app1
      - fastapi_app2
      - fastapi_app3
      - fastapi_app4
