version: "3.8"

services:
  fastapi_app1:
    build: .
    ports:
      - "9000:9000"
    command: [ "python", "main.py", "9000" ]

  fastapi_app2:
    build: .
    ports:
      - "9001:9001"
    command: [ "python", "main.py", "9001" ]

  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8999:8999"
    depends_on:
      - fastapi_app1
      - fastapi_app2
