version: "3.8"

services:
  fastapi_app1:
    container_name: fastapi_app1
    build: .
    ports:
      - "9000:9000"
    command: [ "python", "main.py", "9000", "0" ]
    restart: always


  fastapi_app2:
    container_name: fastapi_app2
    build: .
    ports:
      - "9001:9001"
    command: [ "python", "main.py", "9001", "1" ]
    restart: always


  fastapi_app3:
    container_name: fastapi_app3
    build: .
    ports:
      - "9002:9002"
    command: [ "python", "main.py", "9002", "2" ]
    restart: always


  fastapi_app4:
    container_name: fastapi_app4
    build: .
    ports:
      - "9003:9003"
    command: [ "python", "main.py", "9003", "3" ]
    restart: always


  load_balancer:
    container_name: load_balancer
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8999:8999"
    depends_on:
      - fastapi_app1
      - fastapi_app2
      - fastapi_app3
      - fastapi_app4
    restart: always

